### ISSUE TITLE
As a music-listener, I want to control the mood of the music I listen to so I can listen to music that matches my mood

### ISSUE THREAD

**Issue by emilkovacev** [xlab-classes/cse442-spring2022-team-seashell-anatomy#1]
**Acceptance Tests**

*Test 1*

1. Go to the “playlist generator” page on the website
2. Generate a playlist by filling out the form and clicking the submit button.
3. Scroll through the recommended songs, and select a song to get the details of the song. Namely, the name of the song, the cover art, and the artist who made the song.

**Comment by aleena-sheikh** [comment]
be more specific than playlist page
