### ISSUE TITLE
As a listener with broad tastes, I want distinct playlists generated for me that all have a unique sound and genre of my choosing so I have separate playlists for each mood/genre

### ISSUE THREAD

**Issue by emilkovacev** [xlab-classes/cse442-spring2022-team-seashell-anatomy#10]
**Acceptance Tests**

*Test 1*

1. Go to the “playlist generator” page of the website
2. Set parameters for the 1st playlist. (e.g. parameters that correspond to doom-drone metal)
3. Generate 1st playlist, and save results to a file
4. Set parameters for the 2nd playlist such that the genre/tone of it is distinct from that of the first (e.g. hypnagogic pop)
5. Generate 2nd playlist, and save results to the different files
6. Verify that no songs in the 1st playlist have the same genre/tone as those in the 2nd playlist and vice versa

**Comment by stevenAdrianCarter** [comment]
Not accurate to current and planned feature set. Please change acceptance tests
