### ISSUE TITLE
As a non-expert in music genres, I want the playlist parameters to be simple and/or well explained so I can correctly tune the site to my preferred style of music

### ISSUE THREAD

**Issue by emilkovacev** [xlab-classes/cse442-spring2022-team-seashell-anatomy#12]
**Acceptance Tests**

*Test 1*

1. To ensure the correctness and consistency of the parameters, go to the “playlist generator” page of the site.
2. Check that there are 4 parameters, 1 slider per parameter
    1. acousticness
    2. danceability
    3. energy
    4. valence

3. Check that each slider begins in the middle position
4. Submit the form
5. Validate that a playlist with 10 songs is returned

**Comment by aleena-sheikh** [comment]
what else should this story accomplish? what should the user expect as a result?

**Comment by aleena-sheikh** [comment]
This should also have the sprint 3 tag
