### ISSUE TITLE
Getting Artist names using spotify API

### ISSUE THREAD

**Issue by kazishad** [xlab-classes/cse442-spring2022-team-seashell-anatomy#15]
**Task Tests**

*Task 1*

1) Go to `http://cheshire.cse.buffalo.edu:5001/playlist_gen`
2) Input in your preferred parameters for the playlist
3) Click on the `submit` button
4) Verify that the artist names are underneath the artist columns

**Comment by aleena-sheikh** [comment]
fix task test
