### ISSUE TITLE
Writes to the SQL Database 

### ISSUE THREAD

**Issue by jrnaranj** [xlab-classes/cse442-spring2022-team-seashell-anatomy#16]
**Task tests**

*Test 1*

1.  Log in to the UB SQL server using your credentials.
2. Use the command "USE  cse_442_2022_spring_team_b_db" to select group database.
3. Use the command "SELECT * FROM song_data;" to view the songs in the database.

**Comment by aleena-sheikh** [comment]
add dependencies

**Comment by aleena-sheikh** [comment]
should be blocking the user story
