### ISSUE TITLE
Wireframing using Figma

### ISSUE THREAD

**Issue by stevenAdrianCarter** [xlab-classes/cse442-spring2022-team-seashell-anatomy#18]
Task Test 1:
1. Start Figma presentation
2. click on each of the links on each page and verify they go to the correct page
a. Home button on About and App page
b. About button on Home and App page
c. "Playlist Generator" on Home and About, and "Use Now" on Home

Task Test 2:
1. Start Figma Presentation
2. Go to app page
3. Verify that:
a. The frame listing parameters and their sliders can scroll up and down
b. The frame listing squares (analogous to album covers) scrolls horizontally

**Comment by aleena-sheikh** [comment]
add assignee
