### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by emilkovacev** [xlab-classes/cse442-spring2022-team-seashell-anatomy#19]
Develop the about page (frontend), display each user, and deploy flask app to serve static about page file

Task Test:
1. Clone repository
2. Run the following bash script on the command line
```
`run_server.sh`
```
4. Retrieve <host> and <port> number from output of previous terminal command
5. Verify web server is running on [http://\<host\>:\<port\>/](http://\<host\>:\<port\>/)
6. Verify that [http://\<host\>:\<port\>/about](http://\<host\>:\<port\>/about) resolves to the about.html static page

**Comment by aleena-sheikh** [comment]
simplify task test, you can assume you are on site; no assignee

**Comment by aleena-sheikh** [comment]
task tests still weren't changed
