### ISSUE TITLE
Deploy Hello World

### ISSUE THREAD

**Issue by emilkovacev** [xlab-classes/cse442-spring2022-team-seashell-anatomy#20]
### Task Test
1. ssh to cheshire.cse.buffalo.edu and use `screen -r` to verify that the flask webserver is running
2. Connect to cheshire.cse.buffalo.edu:<port_number> in any web browser
3. Verify that the static hello world page is present

**Comment by aleena-sheikh** [comment]
what is the port number?

**Comment by aleena-sheikh** [comment]
no assignee
