### ISSUE TITLE
Tie together front-end and back-end

### ISSUE THREAD

**Issue by russella26** [xlab-classes/cse442-spring2022-team-seashell-anatomy#25]
**Task Tests**

*Test 1*

1. Run the server from cheshire
1. Verify that the server is running and that the tests have passed completely.
2. Connect to server address `http://cheshire.cse.buffalo.edu:5001/playlist_gen`
3. Navigate to the webpage
4. Navigate to the `/generate_playlist` page
5. Leave all parameters on the form alone (no changes)
6. Click the submit button for the form
7) Verify that page was changed to http://cheshire.cse.buffalo.edu:5001/generate?<url encoded form data>
8) Verify that a playlist is displayed to the user

**Comment by aleena-sheikh** [comment]
more specific tests

**Comment by aleena-sheikh** [comment]
should be blocking the user story
