### ISSUE TITLE
Create a recommendation algorithm

### ISSUE THREAD

**Issue by emilkovacev** [xlab-classes/cse442-spring2022-team-seashell-anatomy#26]
**Task Tests**

*Test 1*

1. Go to http://cheshire.cse.buffalo.edu:5001/
2. click on `/generate_playlist`
3. Fill out the parameters of the form
4. Click submit
5. Ensure that the output displays songs
6. Check each song
  a. Ensure that the parameters for the song are reasonably close to the parameters you entered in the form

**Comment by aleena-sheikh** [comment]
Task tests!

**Comment by aleena-sheikh** [comment]
move this into in progress

**Comment by aleena-sheikh** [comment]
just change step 1 to be the site then what button on the site so donkeykongdecember.com -> click on "playlist generator"

**Comment by stevenAdrianCarter** [comment]
+ Aleena's last comment
