### ISSUE TITLE
Add ratings to SQL Database

### ISSUE THREAD

**Issue by jrnaranj** [xlab-classes/cse442-spring2022-team-seashell-anatomy#27]
**Task tests**

*Test 1*

1. Log in to the UB SQL server using your credentials.
2. Use the command "USE cse_442_2022_spring_team_b_db" to select group database.
3. Use the command "SELECT * FROM song_data;" to view the songs in the database.
4. View the rating column on the displayed table.

**Comment by aleena-sheikh** [comment]
add task tests

**Comment by aleena-sheikh** [comment]
this should be blocking the user story, not blocked by
