### ISSUE TITLE
Add rating form to front end

### ISSUE THREAD

**Issue by stevenAdrianCarter** [xlab-classes/cse442-spring2022-team-seashell-anatomy#28]
**Task Tests**

*Test 1*

1. Go to ratings page by generating a playlist, and clicking on "Rate this playlist"
2. Verify that the rating form contains:
a. A range object from 1-10
b. A text box for manual feedback
3. Verify that the form can be submitted and have the results be able to be passed to the back end

**Comment by aleena-sheikh** [comment]
should be block user story#5

**Comment by aleena-sheikh** [comment]
follow style guide for tests
