### ISSUE TITLE
Augment form structure

### ISSUE THREAD

**Issue by emilkovacev** [xlab-classes/cse442-spring2022-team-seashell-anatomy#32]
**Task Tests**

*Test 1*

1. Open http://cheshire.cse.buffalo.edu:5001/playlist_gen
2. Leave the sliders in the center
3. Click Submit
4. Ensure that any playlist is returned

**Comment by aleena-sheikh** [comment]
change task test to numbered list

**Comment by aleena-sheikh** [comment]
more specific steps. What form?
