### ISSUE TITLE
Finish Main and About Pages 

### ISSUE THREAD

**Issue by jrnaranj** [xlab-classes/cse442-spring2022-team-seashell-anatomy#36]
Task Test:

1. Navigate to http://cheshire.cse.buffalo.edu:5001/about on any web browser
2. Verify that the home page is visible and the "use now" button is there.
3. Click on "About" in the top right corner of the page.
4. Verify that a page is visible that shows images and names of all 5 team members

**Comment by emilkovacev** [comment]
needs a task test!
