### ISSUE TITLE
Update Wireframe

### ISSUE THREAD

**Issue by stevenAdrianCarter** [xlab-classes/cse442-spring2022-team-seashell-anatomy#38]
## Task Test 1
1. Start Figma presentation
2. For each page accessible from the the task bar: (Homepage, About page, Playlist Generator (Parameter) page)
a. verify that each of the links in the taskbar, aside from the entry corresponding to the current page takes the user to the corresponding page.
3. Go to the playlist generator page and submit a form by clicking the "submit" button (contents do not matter)
4. Verify that all links in the task bar takes the user to the corresponding page.

## Task Test 2
1. Start Figma Presentation and click the link in the taskbar that takes the user to the Playlist Generator page (Parameter Page in Figma)
2. Submit the form by clicking the "submit" button (contents do not matter)
3. Verify that the "save ratings" informs the user that their ratings have been "saved".
4. Verify that the "Export to Spotify" button signal to the user that they are about to be redirected to a Spotify login page?.
5. Verify that the "Share" button shows the user an overlay that options for what social media platform they want to post to, and a link to a static page showing the current playlist.

## Task Test 3
1. Start Figma Presentation and click the link in the taskbar that takes the user to the Playlist Generator page (Parameter Page in Figma)
2. Submit the form by clicking the "submit" button (contents do not matter)
3. Verify that clicking on each of the artists' names pulls up an overlay that shows:
a. The artist's name and profile picture
b. A link to an artist page on an external website (possibly Spotify)
c. A list of songs that list the same artist

**Comment by aleena-sheikh** [comment]
Regarding Test 2, I believe we don't need a refresh button, and we would want "Save", "Export to Spotify" and "Share with Friends" buttons. Also can you make them more specific, what should happen when I click "share"? Will I see an overlay modal prompting me to download a file(I should) or is it a single link(probably not)

**Comment by aleena-sheikh** [comment]
What is the external link in 3b?
