### ISSUE TITLE
Update Front-End Based On Wireframe

### ISSUE THREAD

**Issue by jrnaranj** [xlab-classes/cse442-spring2022-team-seashell-anatomy#39]
### Task Test 1

1.  Navigate to http://cheshire.cse.buffalo.edu:5001/about on any web browser
2.  Verify that the home page is visible and the "use now" button is there.
3.  Verify that the home page looks identical to the one in the wireframe.

### Task Test 2

1.  Navigate to http://cheshire.cse.buffalo.edu:5001/about on any web browser
2.  Click on "About" at the top of the page (navigation bar).
3.  Verify that the about page is visible and shows all 5 team members.
4.  Verify that the about page looks identical to the one on the wireframe.

### Task Test 3

1.  Navigate to http://cheshire.cse.buffalo.edu:5001/about on any web browser
2. Verify that the navigation bar has a button for "Home", "About", and "Playlist Generator".
3. Verify that the navigation bar looks identical to the one on the wireframe.

**Comment by aleena-sheikh** [comment]
PLease add a test for artist page

**Comment by aleena-sheikh** [comment]
Please have one test for each page

**Comment by aleena-sheikh** [comment]
also #17 refers only to the wireframe. This should block 13 and 9
