### ISSUE TITLE
Create Artist Pages

### ISSUE THREAD

**Issue by stevenAdrianCarter** [xlab-classes/cse442-spring2022-team-seashell-anatomy#40]
## Task Test 1
1. Go to the "playlist generator" page, enter parameters and press the "submit" button.
2. For each song in the playlist
a. Click on the artist name, and verify that an overlay appears.

## Task Test 2
1. Go to the "playlist generator" page, enter parameters and press the "submit" button.
2. For each song in the playlist, click on the artist's name
a. Verify that overlay contains:
    - The artist's name
    - A link to a search for the artist on Spotify
    - A picture related to the artist: currently 1st song's album cover
    - A list of songs from that artist that are available in the software

**Comment by aleena-sheikh** [comment]
does it have the artist spotify link or artist picture? please check and update tests accordingly
