### ISSUE TITLE
Create an share function that works with our app

### ISSUE THREAD

**Issue by kazishad** [xlab-classes/cse442-spring2022-team-seashell-anatomy#41]
Task Test:

1. Go to `http://128.205.245.140:5001` 
2. Click on green `Use Now` Button
3. Select the preferred parameters for each category
4. Click on the `submit` button
5. Once the playlist is generated, click on the `Share` button
6. The `/share` page should have all playlists generated by previous users. Confirm that your playlist among the other playlists on the page.

**Comment by aleena-sheikh** [comment]
rename the title since our requirements have changed

**Comment by stevenAdrianCarter** [comment]
Is the "share page" just a copy of the generated playlist? I did not get that impression from what you were working on. Change your task tests to test the actual functionality of this feature.

**Comment by aleena-sheikh** [comment]
donkeykongdecember.com leads to something else

**Comment by aleena-sheikh** [comment]
is it all playlists or just the playlists users have chosen to share?

**Comment by aleena-sheikh** [comment]
what is the format of all these playlists?
