### ISSUE TITLE
Export Playlist to Spotify

### ISSUE THREAD

**Issue by russella26** [xlab-classes/cse442-spring2022-team-seashell-anatomy#42]
Task Test 1:
1. Navigate to the playlist generation page (cheshire.cse.buffalo.edu:5001/playlist_gen)
2. Click the button labeled "Submit"
3. Verify that a playlist is displayed, and click the button labeled "Export to Spotify"
4.  Verify that a playlist opens in Spotify with the same songs as before

**Comment by stevenAdrianCarter** [comment]
Question: Are there any cases where there is an invalid entry to the export algorithm?

**Comment by emilkovacev** [comment]
Afaik I don't think there is. Did you have something particular in mind?

**Comment by aleena-sheikh** [comment]
After you click export, will you be prompted to log in? what else can I expect before seeing a created playlist in spotify

**Comment by russella26** [comment]
to adrian: no
to aleena: no, it takes you to seashell anatomy's spotify page, it shouldn't prompt a login
