### ISSUE TITLE
Display Shared Playlists on Seashell Anatomy

### ISSUE THREAD

**Issue by jrnaranj** [xlab-classes/cse442-spring2022-team-seashell-anatomy#43]
### Task Tests

**Test 1:**

1.  Navigate to http://cheshire.cse.buffalo.edu:5001 on any web browser
2. Click on the "Use Now" button.
3. Set the parameters to generate the desired playlist.
4. Verify that a playlist was generated.
5. Navigate http://cheshire.cse.buffalo.edu:5001/share
6. Verify that the playlist was added to the list of shared playlists.

**Comment by aleena-sheikh** [comment]
have you tested with multiple browsers?

**Comment by aleena-sheikh** [comment]
I believe this was a frontend task right? Its a little vague either way
