### ISSUE TITLE
Populate Database with More Songs

### ISSUE THREAD

**Issue by jrnaranj** [xlab-classes/cse442-spring2022-team-seashell-anatomy#44]
### Task Tests

**Test 1:**
1. Log in to the UB SQL server using your credentials.
2. Use the command "USE cse_442_2022_spring_team_b_db" to select group database.
3. Use the command "SELECT * FROM song_data;" to view the songs in the database.
4. Verify that there are 1000 songs in the database.

**Comment by stevenAdrianCarter** [comment]
Define x. Is x the total number of songs? Is it the number of songs added?
