### ISSUE TITLE
Add Table in Database for Exported Playlists

### ISSUE THREAD

**Issue by jrnaranj** [xlab-classes/cse442-spring2022-team-seashell-anatomy#47]
### Task Tests

**Test 1:**
1. Log in to the UB SQL server using your credentials.
2. Use the command "USE cse_442_2022_spring_team_b_db" to select group database.
3. Use the command "SELECT * FROM shared_playlists;" to view the playlists that have been exported.
4. Verify that the table exists and that the playlist is stored in the database as a PickleType (fixed precision numbers, such as NUMERIC or DECIMAL).

**Comment by stevenAdrianCarter** [comment]
What does serialized mean in this context?
