### ISSUE TITLE
Frontend for playlist generator and playlist display,

### ISSUE THREAD

**Issue by russella26** [xlab-classes/cse442-spring2022-team-seashell-anatomy#48]
Task Test 1:
1. Open the playlist generator page (http://128.205.32.39:5001/playlist_gen)
2. Verify that the project website design follows the following standard
  i. Green lined boxes surrounding sliders for each parameter, stretching the length of the page
  ii. In the bottom left corner, after all the above parameters, a button labeled submit that redirects to the playlist return page

Task Test 2:
1. Open the playlist return page (http://128.205.32.39:5001/playlist_gen)
2. Leaving the parameter sliders in the center, click submit
3. Now on the playlist return page, verify that the project website design follows the following standard
  i. Green lined boxes surrounding details for each song, stretching the length of the page
  ii. Album art in the far left
  iii. Correctly labeled columns for Song Name, Artist Name, and Upvotes
  iv. In the bottom left corner, after all the songs, three buttons that function as follows:
    a. "Save Ratings" (currently backend is unimplemented)
    b. "Export to Spotify", when clicked should open up an identical playlist in Spotify
    c. "Share" (currently backend is unimplemented)

**Comment by aleena-sheikh** [comment]
please add some more tests regarding the actual functionality of the front end. What does each button do and what can I expect to show?

**Comment by aleena-sheikh** [comment]
why leave the sliders in the center? shouldn't it work with any combination of parameters?
