### ISSUE TITLE
As a music-listener, I want to rate the music that's recommended to me so I can listen to music that fits my taste

### ISSUE THREAD

**Issue by emilkovacev** [xlab-classes/cse442-spring2022-team-seashell-anatomy#5]
**Acceptance Tests**

*Test 1*

1. Navigate to the playlist recommendation page
2. input a value for accousticness, danceability, energy, valence
3. submit the form
4. Choose one of the 10 generated songs that you thing belongs in the playlist
5. Click the checkbox for that song
6. Reload the page
  a. validate that the recommendations change (with the possibility that some stay)
  b. validate that the values of the song categories change with each reload

**Comment by aleena-sheikh** [comment]
be more specific in step 5

**Comment by aleena-sheikh** [comment]
Are steps 4 and 5 accurate? I was under the impression that there's only one playlist as a result? Either I'm wrong or please change these steps, also specify the buttons clicked to get to a certain page get a result
