### ISSUE TITLE
Add Songs From Request Page to Database

### ISSUE THREAD

**Issue by jrnaranj** [xlab-classes/cse442-spring2022-team-seashell-anatomy#50]
### Task Tests

Test 1:

1. Log in to the UB SQL server using your credentials.
2. Use the command "USE cse_442_2022_spring_team_b_db" to select group database.
3. Use the command "SELECT * FROM song_data;" to view the songs in the database.
4. Verify that the song ID from the request form is in the database.

**Comment by stevenAdrianCarter** [comment]
The songs themselves were not able to be in the database when you moved this to completed. Do you mean the song ID?
