### ISSUE TITLE
Create a share button

### ISSUE THREAD

**Issue by kazishad** [xlab-classes/cse442-spring2022-team-seashell-anatomy#51]
Task Test:
1. Go to `http://128.205.32.39:5001/`
2. Click on `use now`
3. Choose your preferences for the playlist then press the `submit` button
4. Click on the `share` button 
5. Confirm that the button takes you to the right page by looking at the last bit of the url, which should say `/share`

**Comment by stevenAdrianCarter** [comment]
What is the right page?!
