### ISSUE TITLE
Create the front-end for the /share page

### ISSUE THREAD

**Issue by kazishad** [xlab-classes/cse442-spring2022-team-seashell-anatomy#52]
Task Test:
1. Go to `http://128.205.32.39:5001/`
2. Click on `use now`
3. Choose your preferences for the playlist then press the `submit` button
4. Click on the `share` button 
5. Once on the `/share` page, confirm that each playlist has their playlist number right above them and each playlist is separated by the a green bar to distinguish between other playlists.

**Comment by aleena-sheikh** [comment]
please be more specific than playlists are "there"; walk through an example
