### ISSUE TITLE
Store Request Page URI as Song in Database

### ISSUE THREAD

**Issue by jrnaranj** [xlab-classes/cse442-spring2022-team-seashell-anatomy#53]
### Task Tests

Test 1:
1.  Navigate to http://cheshire.cse.buffalo.edu:5001 on any web browser
2. Click on the "Use Now" button.
3. Click the "request song" button.
4. Input a Spotify song URL and press submit.
5. Log in to the UB SQL server using your credentials.
6. Use the command "USE cse_442_2022_spring_team_b_db" to select group database.
7. Use the command "SELECT * FROM song_data;" to view the songs in the database.
8. Verify that the song from the request form is in the database.
9. Verify that not only the song ID is stored, but all of the song's features as well.

Test 2:

1. Navigate to http://cheshire.cse.buffalo.edu:5001 on any web browser
2. Click on the "Use Now" button.
3. Click the "request song" button.
4. Input a Spotify song URL and press submit.
5. Repeat this process once more with the same Spotify song URL.
6. Log in to the UB SQL server using your credentials.
7. Use the command "USE cse_442_2022_spring_team_b_db" to select group database.
8. Use the command "SELECT * FROM song_data;" to view the songs in the database.
9. Verify that the song was not added to the database twice.

**Comment by stevenAdrianCarter** [comment]
At the current moment, the "request" link is on the "parameter page", and not the "playlist page". You do not need to generate the playlist to request a song.

Also, add some tests regarding when the songID already exists in the database to make sure we don't get duplicates.
