### ISSUE TITLE
Improve the front end user experience for the share page

### ISSUE THREAD

**Issue by stevenAdrianCarter** [xlab-classes/cse442-spring2022-team-seashell-anatomy#59]
## Task Test 1
1. Open ```http://cheshire.cse.buffalo.edu:5001/```, go to the playlist generator page, submit parameters and click on the share button.
2. Verify that the design is aesthetically consistent with that of the rest of the site
3. Verify that the site initially collapses the playlists into just their titles for easier scrolling
4. Verify that clicking on a playlist expands the playlists content

**Comment by aleena-sheikh** [comment]
5 is possible but will be a standalone task
