### ISSUE TITLE
Adjust the playlist generator so that each new playlist is unique for that session

### ISSUE THREAD

**Issue by kazishad** [xlab-classes/cse442-spring2022-team-seashell-anatomy#60]
Task Test:

1. Go to `http://cheshire.cse.buffalo.edu:5001/`
2. Click on `Use Now`
3. Select your preferred parameters and click on `Submit`
4. Take note of the songs in the playlist
5. Click on the `Playlist generator` at the top of the page
6. Create generate another playlist with the same parameters as before
7. Confirm that the current playlist is not the same as the old playlist

**Comment by aleena-sheikh** [comment]
move into planned/in-progress

**Comment by stevenAdrianCarter** [comment]
On step 7, we can have some of the same songs, but not all of them.
