### ISSUE TITLE
As a music listener, I want the website to show me a list of artists that wrote those songs so that I can listen to other songs made by them

### ISSUE THREAD

**Issue by emilkovacev** [xlab-classes/cse442-spring2022-team-seashell-anatomy#9]
**Acceptance Tests**

*Test 1*

1. Go to the “playlist generator” page of the website.
2. Set parameters for, and then generate a playlist.
3. For each entry in the playlist:
a. Verify that each of the song entries have an associated artist.
b. Verify that each artist's text links to a relevant page for the artist.
4. In each artists subpage by clicking on the artist link:
a. Verify that there is a comprehensive list of songs from that artist on the page based on the entries in our database.
b. Verify that, if applicable, there is some link to a relevant artist page on an external site and verify that that link takes the user to the specified page
c. If there are multiple artists on a song, verify that clicking on each of the names brings up the respective artist page.
6. In a given artist page, verify that each song corresponds and links to the same song on Spotify.

**Comment by aleena-sheikh** [comment]
what should happen after you click the artist text link? This can use a lot more specific steps
